image: node:latest

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
    paths:
        - node_modules/

run_tests:
    script:
        - npm install
        - npm run test

lint_test:
    script:
        - npm install
        - npm run lint:test
