name: CI
on: [push]
jobs:
    Ubuntu:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                node-version: [10, 12]
                os: [ubuntu-latest]
        steps:
            - run: git config --global core.autocrlf false
            - uses: actions/checkout@v1
            - uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npm install
            - run: npm test
            - run: npm run build
              env:
                  CI: true
    Lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-node@v1
            - run: npm i
            - run: npm run lint:test
